mysql:
  image: mysql:latest
  volumes_from:
   - data
  ports:
   - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: mysql_migrations
    MYSQL_USER: mysql_migrations
    MYSQL_PASSWORD: mysql_migrations

data:
  image: mysql:latest
  volumes:
   - /var/lib/mysql
  command: "true"
